package hr.hpatrik.lordofthequotes.view.main

import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import hr.hpatrik.lordofthequotes.api.AIQuoteApi
import hr.hpatrik.lordofthequotes.model.AIQuoteRequestMessage
import hr.hpatrik.lordofthequotes.model.AIQuoteRequestBody
import org.json.JSONObject
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

@ExperimentalAnimationApi
@Composable
fun AboutScreen(modifier: Modifier = Modifier) {

    val QUOTE_AI_API_URL = " https://api.openai.com/v1/chat/"

    val retrofit = Retrofit.Builder()
        .baseUrl(QUOTE_AI_API_URL)
        .addConverterFactory(GsonConverterFactory.create())
        .build()


    val apiService = retrofit.create(AIQuoteApi::class.java)
    val lotrCharacters =
        listOf("Frodo Baggins", "Samwise Gamgee", "Gandalf", "Aragorn", "Legolas", "Gimli")
    val randomCharacter by remember {
        mutableStateOf(lotrCharacters.random())
    }

    val message = AIQuoteRequestMessage("user", "Create a $randomCharacter style quote")
    val messages = listOf(message)
    val requestBody = AIQuoteRequestBody("gpt-3.5-turbo", messages, 0.7)


    var quoteResponse by remember {
        mutableStateOf("")
    }


    LaunchedEffect(Unit) {
        val result = apiService.getAIQuote(requestBody = requestBody)
        val jsonResponse = result.body()?.string() ?: ""
        val jsonObject = JSONObject(jsonResponse)
        val messageObject =
            jsonObject.getJSONArray("choices").getJSONObject(0).getJSONObject("message")
        val generatedMessage = messageObject.getString("content")
        quoteResponse = generatedMessage

    }
    AboutCards(quoteResponse, randomCharacter)
}


@Composable
fun AboutCards(quoteResponse: String = "", randomCharacter: String = "") {
    Surface(
        modifier = Modifier
            .fillMaxSize()
            .padding(bottom = 10.dp),
        color = MaterialTheme.colors.background
    ) {
        Column(
            modifier = Modifier
                .padding(16.dp)
                .verticalScroll(rememberScrollState())
        ) {

            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                elevation = 4.dp
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    Text(
                        text = "Lord of the Quotes",
                        style = MaterialTheme.typography.h4
                    )
                    Text(
                        text = "Version 1.0.0",
                        style = MaterialTheme.typography.subtitle1
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = "An app for Lord of the Rings quotes and soundtrack",
                        style = MaterialTheme.typography.body1
                    )
                }
            }

            Spacer(modifier = Modifier.height(8.dp))
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                elevation = 4.dp,
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    if (quoteResponse.isEmpty()) {
                        Text(
                            text = "AI generated Quote:",
                            style = MaterialTheme.typography.h5
                        )
                        Spacer(modifier = Modifier.height(16.dp))
                        CircularProgressIndicator(
                            modifier = Modifier.size(24.dp),
                            strokeWidth = 2.dp
                        )
                    } else {
                        Text(
                            text = "AI generated $randomCharacter Quote:",
                            style = MaterialTheme.typography.h5
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(
                            text = quoteResponse,
                            style = MaterialTheme.typography.body1
                        )
                    }
                    if (!quoteResponse.isEmpty()) {
                        Text(
                            text = "Disclaimer: This quote was generated by GPT-3 and not actually spoken by $randomCharacter. Please don't hold it against him.",
                            style = MaterialTheme.typography.caption,
                            modifier = Modifier.padding(top = 8.dp)
                        )
                    }
                }
            }
            Spacer(modifier = Modifier.height(8.dp))

            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                elevation = 4.dp
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    Text(
                        text = "Author:",
                        style = MaterialTheme.typography.subtitle1
                    )
                    Text(
                        text = "Patrik Horvat",
                        style = MaterialTheme.typography.body1
                    )
                    Text(
                        text = "phorva2@racunarstvo.hr",
                        style = MaterialTheme.typography.body1
                    )
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                elevation = 4.dp
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    Text(
                        text = "Copyright © 2023 LordOfTheQuotes",
                        style = MaterialTheme.typography.body2
                    )
                    Text(
                        text = "All rights reserved.",
                        style = MaterialTheme.typography.body2
                    )
                }
            }
        }
    }
}



